version: '2'
services:
  canal_cni:
    image: canal_cni:latest
    privileged: true
    network_mode: host
    depends_on:
      - canal-etcd
    labels:
      io.rancher.sidekicks: cni-driver
      io.rancher.scheduler.global: 'true'
      io.rancher.container.dns: 'true'
    volumes:
      - /var/run/calico:/var/run/calico:rw
      - /var/log/calico:/var/log/calico:rw
    environment:
      ETCD_ENDPOINTS: 'http://canal-etcd.canal.rancher.internal:2379'
      IP_AUTODETECT_METHOD: 'can-reach=www.google.com'
  cni-driver:
    privileged: true
    image: canal_cni:latest
    command: sh
    tty: true
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'canal_cni'
      io.rancher.container.dns: 'true'
  canal-agent:
    image: canal-agent:latest
    network_mode: host
    entrypoint:
      - /bin/sh
    environment:
      ETCD_ENDPOINTS: 'http://canal-etcd.canal.rancher.internal:2379'
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'

  canal-controller:
    image: canal-controller:v1.0.2
    network_mode: host
    entrypoint:
      - /bin/sh
    environment:
      ETCD_ENDPOINTS: 'http://canal-etcd.canal.rancher.internal:2379'
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
  canal-etcd:
    image: etcd:latest
    network_mode: host
    labels:
      io.rancher.container.dns: 'true'
    command:
      - etcd
      - -advertise-client-urls
      - http://canal-etcd.canal.rancher.internal:2379
      - -listen-client-urls
      - http://0.0.0.0:2379,http://0.0.0.0:4001
