.catalog:
  name: "Canal"
  version: "v1.0.2"    # Keep this in sync with ican tag version

ican:
  network_driver:
    name: Canal
    default_network:
      name: canal
      host_ports: true
    cni_config:
      '10-rancher-canal.conf':
        name: rancher-canal-network
        type: canal_cni
        log_level: info
        etcd_endpoints: http://canal-etcd.canal.rancher.internal:2379
        ipam:
          type: host-local
