.catalog:
  name: "Calico"
  version: "v1.0.2"    # Keep this in sync with calico/node tag version

calico:
  network_driver:
    name: Calico
    default_network:
      name: calico
      host_ports: true
    cni_config:
      '10-rancher-calico.conf':
        name: rancher-calico-network
        type: calico
        log_level: info
        etcd_endpoints: http://calico-etcd.calico.rancher.internal:2379
        ipam:
          type: calico-ipam
